# Generated by Django 4.2.6 on 2023-10-10 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('pid', models.IntegerField(primary_key='True', serialize=False)),
                ('pname', models.CharField(max_length=10)),
                ('pcost', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pmfdt', models.DateField()),
                ('pexpdt', models.DateField()),
            ],
        ),
    ]
